package geneticEmblem.units.factory;

import java.util.ArrayList;

import geneticEmblem.units.generated.*;

public class ClassList {

	ArrayList<Unit> releasedClasses = new ArrayList<>();

	public ClassList() {
		releasedClasses.add(new Amelia());
		releasedClasses.add(new Artur());
		releasedClasses.add(new Astrid());
		releasedClasses.add(new Barst());
		releasedClasses.add(new Bartre());
		releasedClasses.add(new Boyd());
		// releasedClasses.add(new Brom());
		releasedClasses.add(new Canas());
		releasedClasses.add(new Colm());
		releasedClasses.add(new Cormag());
		releasedClasses.add(new Dart());
		// releasedClasses.add(new Dorcas());
		releasedClasses.add(new Eirika());
		releasedClasses.add(new Eliwood());
		releasedClasses.add(new Erk());
		releasedClasses.add(new Ewan());
		releasedClasses.add(new Farina());
		// releasedClasses.add(new Fiora());
		// releasedClasses.add(new Florina());
		releasedClasses.add(new Franz());
		releasedClasses.add(new Garcia());
		releasedClasses.add(new Gatrie());
		releasedClasses.add(new Geoffrey());
		releasedClasses.add(new Gerik());
		releasedClasses.add(new Gilliam());
		releasedClasses.add(new Guy());
		releasedClasses.add(new Haar());
		// releasedClasses.add(new Heath());
		releasedClasses.add(new Ike());
		// releasedClasses.add(new Ilyana());
		releasedClasses.add(new Innes());
		// releasedClasses.add(new Jaffar());
		// releasedClasses.add(new Janaff());
		releasedClasses.add(new Jill());
		releasedClasses.add(new Joshua());
		releasedClasses.add(new Karel());
		releasedClasses.add(new Kent());
		releasedClasses.add(new Kieran());
		releasedClasses.add(new Knoll());
		releasedClasses.add(new Kyle());
		releasedClasses.add(new Larachel());
		releasedClasses.add(new Largo());
		releasedClasses.add(new Lowen());
		// releasedClasses.add(new Lucius());
		releasedClasses.add(new Lute());
		releasedClasses.add(new Lyn());
		releasedClasses.add(new Lyon());
		releasedClasses.add(new Makalov());
		// releasedClasses.add(new Marcia());
		releasedClasses.add(new Marisa());
		releasedClasses.add(new Marth());
		releasedClasses.add(new Mia());
		releasedClasses.add(new Natasha());
		releasedClasses.add(new Neimi());
		releasedClasses.add(new Nephenee());
		releasedClasses.add(new Nino());
		releasedClasses.add(new Oscar());
		releasedClasses.add(new Pent());
		releasedClasses.add(new Priscilla());
		// releasedClasses.add(new Rath());
		// releasedClasses.add(new Raven());
		releasedClasses.add(new Rebecca());
		releasedClasses.add(new Rhys());
		// releasedClasses.add(new Rolf());
		releasedClasses.add(new Ross());
		releasedClasses.add(new Sain());
		releasedClasses.add(new Serra());
		releasedClasses.add(new Shinon());
		releasedClasses.add(new Soren());
		// releasedClasses.add(new Sothe());
		// releasedClasses.add(new Stefan());
		releasedClasses.add(new Tana());
		releasedClasses.add(new Tanith());
		releasedClasses.add(new Tormod());
		releasedClasses.add(new Ulki());
		releasedClasses.add(new Ephraim());
		releasedClasses.add(new Hector());
		releasedClasses.add(new Oswin());
		releasedClasses.add(new Volke());
		releasedClasses.add(new Wil());
		releasedClasses.add(new Zihark());
	}

	public ArrayList<Unit> getReleasedUnits() {
		return releasedClasses;
	}
}

// releasedClasses.add(new Ranulf());
// releasedClasses.add(new Tharja());
// releasedClasses.add(new Tiki());
// releasedClasses.add(new Ena());
// releasedClasses.add(new Vaike());
// releasedClasses.add(new Virion());
// releasedClasses.add(new Panne());
// releasedClasses.add(new Felicia());
// releasedClasses.add(new Frederick());
// releasedClasses.add(new Gaius());
// releasedClasses.add(new Rinkah());
// releasedClasses.add(new Henry());
// releasedClasses.add(new Hinata());
// releasedClasses.add(new Hinoka());
// releasedClasses.add(new Izana());
// releasedClasses.add(new Cherche());
// releasedClasses.add(new Cordelia());
// releasedClasses.add(new Chrom());
// releasedClasses.add(new Elise());
// releasedClasses.add(new Yukimura());
// releasedClasses.add(new Arthur());
// releasedClasses.add(new Effie());
// releasedClasses.add(new Odin());
// releasedClasses.add(new Ryoma());
// releasedClasses.add(new Saizo());
// releasedClasses.add(new Niles());
// releasedClasses.add(new Subaki());
// releasedClasses.add(new Sully());
// releasedClasses.add(new Sumia());
// releasedClasses.add(new Nyx());
// releasedClasses.add(new Camilla());
// releasedClasses.add(new Azama());
// releasedClasses.add(new Shura());
// releasedClasses.add(new Silas());
// releasedClasses.add(new Setsuna());
// releasedClasses.add(new Stahl());
// releasedClasses.add(new Anna());
// releasedClasses.add(new Azura());
// releasedClasses.add(new Selena());
//	releasedClasses.add(new Takumi());
// releasedClasses.add(new Miriel());
// releasedClasses.add(new Mordecai());
// releasedClasses.add(new Lethe());
// releasedClasses.add(new Libra());
// releasedClasses.add(new Lissa());
// releasedClasses.add(new Lonque());
//	releasedClasses.add(new Mozu());
// releasedClasses.add(new Sakura());
// releasedClasses.add(new Sayri());
// releasedClasses.add(new Ricken());
// releasedClasses.add(new Leo());
// releasedClasses.add(new Keaton());
// releasedClasses.add(new Xander());
// releasedClasses.add(new Flora());
// releasedClasses.add(new Robin());
// releasedClasses.add(new Donnel());
// releasedClasses.add(new Jakob());
// releasedClasses.add(new Scarlet());
// releasedClasses.add(new Beruka());
// releasedClasses.add(new Gregor());
// releasedClasses.add(new Gunter());
// releasedClasses.add(new Hana());
// releasedClasses.add(new Kaze());
// releasedClasses.add(new Kellam());
// releasedClasses.add(new Hayato());
// releasedClasses.add(new Nowi());
// releasedClasses.add(new Kaden());
// releasedClasses.add(new Maribelle());
// releasedClasses.add(new Kagero());
// releasedClasses.add(new Oboro());
// releasedClasses.add(new Orochi());
// releasedClasses.add(new Laslow());
// releasedClasses.add(new Peri());
// releasedClasses.add(new Benny());
// releasedClasses.add(new Charlotte());
// releasedClasses.add(new Muarim());
// releasedClasses.add(new Naesala());
// releasedClasses.add(new Tibarn());